"""Build a minimal .app bundle for background dictation.

Why a bundle at all, when the code is plain Python: macOS attributes TCC
permissions to a *bundle*, and several of them cannot be granted without one.

* **Microphone** requires ``NSMicrophoneUsageDescription`` in an Info.plist.
  A bare interpreter launched by launchd has no Info.plist, so the request
  cannot even be made — the app is handed silence forever. That is exactly
  the ``[no audio captured]`` loop the LaunchAgent hit.
* The Settings panes then list a generic **"Python"** (or nothing at all),
  which is both confusing and fragile: every venv's interpreter looks alike.
* An ad-hoc signature gives the bundle a stable identity, so the grants
  survive restarts.

The bundle is a thin wrapper: ``Contents/MacOS/<exe>`` is a shell script that
execs the current interpreter on ``python -m openjarvis.cli dictate``. No
compilation, no Xcode, no Rust — the Python stays the source of truth.
"""

from __future__ import annotations

import os
import plistlib
import shutil
import subprocess
import sys
from pathlib import Path

BUNDLE_ID = "com.openjarvis.dictation"
BUNDLE_NAME = "OpenJarvis Dictation"
EXECUTABLE_NAME = "openjarvis-dictate"

_MIC_REASON = (
    "OpenJarvis records audio only while you hold the dictation key, "
    "so it can turn your speech into text on this Mac."
)
_INPUT_REASON = (
    "OpenJarvis watches for the dictation hotkey so you can start "
    "dictating from any application."
)


def default_bundle_path() -> Path:
    """Install under ~/Applications: no admin rights, per-user, stable path."""
    return Path.home() / "Applications" / f"{BUNDLE_NAME}.app"


def build_info_plist() -> dict:
    """The Info.plist contents. Kept pure so tests can assert on it."""
    return {
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleName": BUNDLE_NAME,
        "CFBundleDisplayName": BUNDLE_NAME,
        "CFBundleExecutable": EXECUTABLE_NAME,
        "CFBundlePackageType": "APPL",
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundleShortVersionString": "1.0",
        "CFBundleVersion": "1",
        # Agent, not a windowed app: no Dock icon, no menu bar takeover.
        "LSUIElement": True,
        "LSMinimumSystemVersion": "11.0",
        # Without this key macOS cannot grant Microphone at all.
        "NSMicrophoneUsageDescription": _MIC_REASON,
        # Shown when the process asks to observe input.
        "NSInputMonitoringUsageDescription": _INPUT_REASON,
    }


def build_launcher_script(python: str, workdir: str = "") -> str:
    """The Contents/MacOS script. Execs the interpreter, replacing the shell.

    ``exec`` matters: launchd tracks the process it started, so the Python
    must *become* that process rather than be a child of a shell that exits.

    It deliberately runs from ``$HOME`` and never ``cd``s into the project.
    The project may live under a TCC-protected folder (~/Downloads, ~/Desktop,
    ~/Documents): the app has no file access there, so the ``cd`` fails and
    every later shell call inherits a broken cwd
    (``getcwd: Operation not permitted``). The interpreter already knows where
    the package is — the working directory is irrelevant to dictation.

    ``workdir`` is accepted and ignored, so callers need not special-case it.
    """
    return (
        "#!/bin/sh\n"
        "# Generated by `jarvis dictate-service install` — do not edit.\n"
        'cd "$HOME" || exit 1\n'
        f'exec "{python}" -m openjarvis.cli dictate "$@"\n'
    )


def executable_path(bundle: Path) -> Path:
    return bundle / "Contents" / "MacOS" / EXECUTABLE_NAME


def build(
    dest: Path | None = None,
    *,
    python: str | None = None,
    workdir: str | None = None,
) -> Path:
    """Create (or replace) the .app bundle. Returns its path."""
    bundle = Path(dest) if dest else default_bundle_path()
    contents = bundle / "Contents"
    macos = contents / "MacOS"

    if bundle.exists():
        shutil.rmtree(bundle)
    macos.mkdir(parents=True, exist_ok=True)

    with open(contents / "Info.plist", "wb") as fh:
        plistlib.dump(build_info_plist(), fh)

    exe = macos / EXECUTABLE_NAME
    exe.write_text(
        build_launcher_script(
            python or sys.executable,
            workdir or str(Path.cwd()),
        ),
        encoding="utf-8",
    )
    exe.chmod(0o755)

    _codesign(bundle)
    return bundle


def _codesign(bundle: Path) -> None:
    """Ad-hoc sign so the bundle has a stable identity for TCC.

    Best effort: an unsigned bundle still works, it just re-prompts more
    often, so a missing codesign tool must not fail the install.
    """
    try:
        subprocess.run(
            ["codesign", "--force", "--deep", "--sign", "-", str(bundle)],
            capture_output=True,
            check=False,
        )
    except OSError:
        pass


def is_installed(bundle: Path | None = None) -> bool:
    path = Path(bundle) if bundle else default_bundle_path()
    exe = executable_path(path)
    return exe.is_file() and os.access(exe, os.X_OK)
